apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-redis
  template:
    metadata:
      labels:
        app: ds-redis
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ds-redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: ds-redis
spec:
  ports:
  - port: 6379
  selector:
    app: ds-redis

