version: 1.0
provider:
  name: openfaas
  gateway: http://40.119.49.149:8080
functions:
  register-user:
    lang: python3
    handler: ./register-user
    image: ledgedash/register-user:latest
  social-graph-insert-user:
    lang: python3
    handler: ./social-graph-insert-user
    image: ledgedash/social-graph-insert-user:latest

  social-graph-follow:
    lang: python3
    handler: ./social-graph-follow
    image: ledgedash/social-graph-follow:latest

  register-user-with-id:
    lang: python3
    handler: ./register-user-with-id
    image: ledgedash/register-user-with-id:latest

  get-user-id:
    lang: python3
    handler: ./get-user-id
    image: ledgedash/get-user-id:latest

  social-graph-get-followers:
    lang: python3
    handler: ./social-graph-get-followers
    image: ledgedash/social-graph-get-followers:latest

  social-graph-get-followees:
    lang: python3
    handler: ./social-graph-get-followees
    image: ledgedash/social-graph-get-followees:latest

  social-graph-unfollow:
    lang: python3
    handler: ./social-graph-unfollow
    image: ledgedash/social-graph-unfollow:latest

  social-graph-unfollow-with-username:
    lang: python3
    handler: ./social-graph-unfollow-with-username
    image: ledgedash/social-graph-unfollow-with-username:latest

  social-graph-follow-with-username:
    lang: python3
    handler: ./social-graph-follow-with-username
    image: ledgedash/social-graph-follow-with-username:latest

