version: 1.0
provider:
  name: openfaas
  gateway: http://40.119.49.149:8080
functions:
  register-user:
    lang: python3
    handler: ./register-user
    image: ledgedash/register-user:latest
  social-graph-insert-user:
    lang: python3
    handler: ./social-graph-insert-user
    image: ledgedash/social-graph-insert-user:latest

  social-graph-follow:
    lang: python3
    handler: ./social-graph-follow
    image: ledgedash/social-graph-follow:latest

  register-user-with-id:
    lang: python3
    handler: ./register-user-with-id
    image: ledgedash/register-user-with-id:latest

  get-user-id:
    lang: python3
    handler: ./get-user-id
    image: ledgedash/get-user-id:latest

  social-graph-get-followers:
    lang: python3
    handler: ./social-graph-get-followers
    image: ledgedash/social-graph-get-followers:latest

  social-graph-get-followees:
    lang: python3
    handler: ./social-graph-get-followees
    image: ledgedash/social-graph-get-followees:latest

  social-graph-unfollow:
    lang: python3
    handler: ./social-graph-unfollow
    image: ledgedash/social-graph-unfollow:latest

  social-graph-unfollow-with-username:
    lang: python3
    handler: ./social-graph-unfollow-with-username
    image: ledgedash/social-graph-unfollow-with-username:latest

  social-graph-follow-with-username:
    lang: python3
    handler: ./social-graph-follow-with-username
    image: ledgedash/social-graph-follow-with-username:latest

  media-front-upload-media:
    lang: dockerfile
    handler: ./media-front-upload-media
    image: ledgedash/media-front-upload-media:latest
    environment:
        BLOB_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=davidhliu2020sfaas;AccountKey=dNrgfTFfCcINupXC0tnLaDxmkVeFnQhq0cFn8UO+WwOlzYiyLuZSY6bwSmAt4TkehFCkFBuNLgDvTAEBVERPKQ==;EndpointSuffix=core.windows.net"
        CONTAINER_NAME: "deathstar-media"

  compose-post-frontend:
    lang: python3
    handler: ./compose-post-frontend
    image: ledgedash/compose-post-frontend:latest

  user-service-upload-creator-with-user-id:
    lang: python3
    handler: ./user-service-upload-creator-with-user-id
    image: ledgedash/user-service-upload-creator-with-user-id:latest

  unique-id-service-upload-unique-id:
    lang: python3
    handler: ./unique-id-service-upload-unique-id
    image: ledgedash/unique-id-service-upload-unique-id:latest

  media-service-upload-media:
    lang: python3
    handler: ./media-service-upload-media
    image: ledgedash/media-service-upload-media:latest

  text-service-upload-text:
    lang: python3
    handler: ./text-service-upload-text
    image: ledgedash/text-service-upload-text:latest

  compose-post-service-upload-creator:
    lang: python3
    handler: ./compose-post-service-upload-creator
    image: ledgedash/compose-post-service-upload-creator:latest
    environment:
        REDIS_SERVER: "ds-redis.default"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6

  compose-post-service-upload-unique-id:
    lang: python3
    handler: ./compose-post-service-upload-unique-id
    image: ledgedash/compose-post-service-upload-unique-id:latest
    environment:
        REDIS_SERVER: "ds-redis.default"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6


  compose-post-service-upload-media:
    lang: python3
    handler: ./compose-post-service-upload-media
    image: ledgedash/compose-post-service-upload-media:latest
    environment:
        REDIS_SERVER: "ds-redis.default"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6


  compose-post-service-upload-urls:
    lang: python3
    handler: ./compose-post-service-upload-urls
    image: ledgedash/compose-post-service-upload-urls:latest
    environment:
        REDIS_SERVER: "ds-redis.default"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6


  compose-post-service-upload-user-mentions:
    lang: python3
    handler: ./compose-post-service-upload-user-mentions
    image: ledgedash/compose-post-service-upload-user-mentions:latest
    environment:
        REDIS_SERVER: "ds-redis.default"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6


  compose-post-service-upload-text:
    lang: python3
    handler: ./compose-post-service-upload-text
    image: ledgedash/compose-post-service-upload-text:latest
    environment:
        REDIS_SERVER: "ds-redis.default"
        REDIS_PORT: 6379
        REDIS_EXPIRE_TIMEOUT: 60
        NUM_COMPONENTS : 6


  url-shorten-service-upload-urls:
    lang: python3
    handler: ./url-shorten-service-upload-urls
    image: ledgedash/url-shorten-service-upload-urls:latest
    environment:
        MONGO_URI: "mongodb://mongo-0.mongo.default"

  user-mention-service-upload-user-mentions:
    lang: python3
    handler: ./user-mention-service-upload-user-mentions
    image: ledgedash/user-mention-service-upload-user-mentions:latest
    environment:
        MONGO_URI: "mongodb://mongo-0.mongo.default"

  compose-post-service-compose-and-upload:
    lang: python3
    handler: ./compose-post-service-compose-and-upload
    image: ledgedash/compose-post-service-compose-and-upload:latest

